- name: copying mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: updatng mongodb config
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start mongod service
  ansible.builtin.service:
    name: mongod
    state: started

- name: downloading and extracting schema
  ansible.builtin.unarchive:
    src: "https://github.com/stans-robot-project/mongodb/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: inject the catalogue and users schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop: 
    - catalogue
    - users