#a fact is nothing but property of a machine

- name: demo shell module
  hosts: all
  tasks:
    - name: task 1
      ansible.builtin.shell: uptime
      register: out
    
    - name: task 2
      ansible.builtin.debug:
        msg: "{{out.stdout}}"

    - name: declaring the variable
      ansible.builtin.set_fact:
        STATUS: "{{out.rc}}"