#a fact is nothing but property of a machine

- name: demo shell module
  hosts: all
  tasks:
    - name: task 1
      ansible.builtin.shell: uptime
      register: out
    
    - name: task 1
      ansible.builtin.debug:
        msg: "{{out.stdout}}"