- name: configuring the repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash - 

- name: install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Add the user roboshop
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: roboshop service account

- name: downloading and extracting catalogue
  ansible.builtin.unarchive:
    src: "https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip"
    dest: /tmp
    remote_src: yes                   #tell the source is not local, it is remote

- name: cleanup old content
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: absent    

- name: Copying roboshop files
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
    remote_src: yes 

- name: Install node.js package
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: updating catalogue sytemd service
  ansible.builtin.replace:
    path: /home/{{APPUSER}}/{{COMPONENT}}/systemd.service
    regexp: 'MONGO_DNSNAME'
    replace: '44.211.238.23'

- name: updating catalogue sytemd service
  ansible.builtin.replace:
    path: /home/{{APPUSER}}/{{COMPONENT}}/systemd.service
    regexp: 'REDIS_ENDPOINT'
    replace: 'redis-dev.roboshop.internal'

- name: Copying systemd files
  ansible.builtin.copy:
    src: /home/roboshop/{{COMPONENT}}/systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service
    remote_src: yes 

- name: restarting the service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: started
    enabled: true

- name: set-hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}

# - name: clearing old html content
#   ansible.builtin.file:
#     path: /usr/share/nginx/html/
#     state: absent

# - name: copying frontend content
#   ansible.builtin.copy:
#     src: /tmp/frontend-main/static/
#     dest: /usr/share/nginx/html/
#     remote_src: yes 

# - name: copying nginx content
#   ansible.builtin.copy:
#     src: roboshop.conf
#     dest: /etc/nginx/default.d/roboshop.conf
#   notify: restart nginx

# - name: start frontend service
#   ansible.builtin.service:
#     name: nginx
#     state: start
#     enabled: true