
- name: Copying repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: install mysql
  ansible.builtin.yum:
    name: 
      - mysql-community-server
      - MySQL-python
    state: present

- name: starting the service
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: true

- name: Connecting using default passowrd
  block:
    - name: grabbing the error
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{DB_PASSWORD}}"
        filter: version

  rescue:
    - name: reading mysql log file
      ansible.builtin.slurp:
        src: /var/log/mysqld.log
      register: mysql_log

    - name: copying password change command
      ansible.builtin.copy: 
        src: root-pass.sql
        dest: /tmp/root-pass.sql


    - name: declaring the fact in a variable
      ansible.builtin.set_fact: 
        DEFAULT_PASS: "{{mysql_log['content'] | b64decode | redex_findall('temporary password.*') | join(' ') | split(' ') | last}}"

    - name: changing default passowrd
      ansible.builin.shell: mysql --connect-expired-password -uroot -p{{DEFAULT_PASS}} < /tmp/root-pass.sql







# - name: resetting password block
#   when: MYSQL_STAT.failed
#   ignore_errors: yes
#   block:
#     - name: fething the default password
#       ansible.builtin.shell: grep ""temporary password" /var/log/mysqld.log | awk '{print $NF}'
#       register: DEFAULT_ROOT_PASSWORD

#     - name: Copying password
#       ansible.builtin.copy:
#         src: root-pass.sql
#         dest: /tmp/root-pass.sql

#     - name: resetting the default password
#       ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{DEFAULT_ROOT_PASSWORD}" < /tmp/root-pass.sql
#       register: reset_ROOT_PASSWORD



# - name: configuring the repo
#   ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash - 

# - name: install nodejs
#   include_role:
#     name: common
#     tasks_from: nodejs

# - name: updating catalogue sytemd service
#   ansible.builtin.replace:
#     path: /home/{{APPUSER}}/{{COMPONENT}}/systemd.service
#     regexp: 'MONGO_DNSNAME'
#     replace: '44.211.238.23'

# - name: complete and restart
#   include_role:
#     name: common
#     tasks_from: coandre
