- name: configuring the repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash - 

- name: install nodejs
  include_role:
    name: common
    tasks_from: nodejs

- name: updating catalogue sytemd service
  ansible.builtin.replace:
    path: /home/{{APPUSER}}/{{COMPONENT}}/systemd.service
    regexp: 'MONGO_DNSNAME'
    replace: '44.211.238.23'

- name: complete and restart
  include_role:
    name: common
    tasks_from: coandre
