- name: Copying systemd files
  ansible.builtin.copy:
    src: /home/roboshop/{{COMPONENT}}/systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service
    remote_src: yes 

- name: restarting the service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: started
    enabled: true
    daemon_reload: true

- name: set-hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}