- name: install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Add the user roboshop
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: roboshop service account

- name: downloading and extracting catalogue
  ansible.builtin.unarchive:
    src: "https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip"
    dest: /tmp
    remote_src: yes                   #tell the source is not local, it is remote

- name: cleanup old content
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: absent    

- name: Copying roboshop files
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
    remote_src: yes 

- name: Install node.js package.
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/