- name: configuring the repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash - 

- name: install nodejs
  include_role:
    name: common
    tasks_from: nodejs

- name: updating catalogue sytemd service
  ansible.builtin.replace:
    path: /home/{{APPUSER}}/{{COMPONENT}}/systemd.service
    regexp: 'CATALOGUE_ENDPOINT'
    replace: 'catalogue-qa.roboshop.internal'

- name: updating redis sytemd service
  ansible.builtin.replace:
    path: /home/{{APPUSER}}/{{COMPONENT}}/systemd.service
    regexp: 'REDIS_ENDPOINT'
    replace: 'redis-dev.roboshop.internal'

- name: complete and restart
  include_role:
    name: common
    tasks_from: coandre